pipeline {
    agent any
    environment {
        BRANCH_NAME = "${env.GIT_BRANCH}"
    }
    stages {
        stage('Checkout') {
            steps {
                git url: 'https://github.com/savindu-pasintha/msdocs-python-flask-webapp-quickstart.git', branch: "${BRANCH_NAME}"
            }
        }
        
        stage('List Files') {
            steps {
                // List files in the workspace
                echo "folder"
                sh "pwd"
                sh 'ls -la'
            }
        }
    }

    // post {
    //     always {
    //         // Clean up
    //         sh 'deactivate'
    //     }
    //     success {
    //         echo 'Pipeline completed successfully.'
    //     }
    //     failure {
    //         echo 'Pipeline failed.'
    //     }
    // }
}
