pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git url: 'https://github.com/savindu-pasintha/msdocs-python-flask-webapp-quickstart.git', branch: 'main'
            }
        }

        stage('Build') {
            steps {
                echo 'Building Backend 1...'
                // Add your build steps here
            }
        }

        stage('Test') {
            steps {
                echo 'Testing Backend 1...'
                // Add your test steps here
            }
        }

        stage('Deploy') {
            steps {
                echo 'Deploying Backend 1...'
                // Add your deploy steps here
            }
        }
    }
}

